// <auto-generated />
namespace AcademyPortalDaLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class update_id : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update_id));
        
        string IMigrationMetadata.Id
        {
            get { return "202105081534433_update_id"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
